{% set name = "pyCompare" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 593a3e6854d8ba3dd0e037500e109c691e8231ec30e93efdc33509314c91059e

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.14.2
    - scipy >=1.0.1
    - matplotlib-base >=3.0.2

test:
  imports:
    - pyCompare

about:
  home: https://github.com/jaketmp/pyCompare
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A Python module for generating Bland-Altman plots to compare two sets of measurements.'

extra:
  recipe-maintainers:
    - hoechenberger
