travis:
  secure:
    BINSTAR_TOKEN: pS4r75Sm3uo+3omaojmKfDuNzeY3c1pkQwPgnfctvt0dn4mALSBf5TCAILdSGvdunEsoOrv5FnqoOd1TnsoXz9ddngXF94AQogZfEX0gChVVbAxOHy31PRabTOGHHFO/jM++eWu/Xjeu1I/TKbie+Ms3iEBcQPdQb0V8YAQEEluhkx0ofGFQo7O6PgLX1jYOUvm/4V4CB3GqKLJgPkagLMin3RS3OCYy43JY4KScCbcr8Z7fFFVtq766VHYX3luWAxNVXxJbc7MK7wBFpQvgZxLcu36nCtTV8pbWoLi10o/nQjhzP0cC9n/50Ixw1soBYr3RY0culDzcHiIgy4N1p0yrIAt7N3IB83JkLHe1dFMRhUpcl680Hs5Le5oGDXLiXiCseoKXKQBIrBhp98ZQKHTpjwgr2e3pSXPeZ2qHuI27OMMkHi3Rtl+fxWjug99MWkAzzBhgqsNYSZAEkFfQsKRZhU6S2FifKMf/W1y4+IbsiWCwxX7KgMv04muzEZem1FoHqcdT3fSdJRnC7SDBeZQhwVZ2aCCPpICARsx38Q5Ffg8ZowlPf0DWTMSN5ZcXb0fcFVtU3ObtEi3gag7HYu0S5jq0v9gPvuK8CduTiCMXc+3vHcfJQVaewsB/v3Rz+vSazuXiSyQaXWfoXmu0jnPRYzb8RvoXRfzLvEwQ3i0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
